### ISSUE TITLE
time consuming by mpirun invoke

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#103]
hi~
I do a test with 2node , each node has 8 Gpus. 
print the  startime in the python script `tf_cnn_benchmarks.py`

**case A:**
```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-horovod-2
spec:
  replicas: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5 
        args:
         - cd /code &&  mpirun -x NCCL_DEBUG=INFO python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
        command:
         - /bin/bash
         - -c
        imagePullPolicy: Always
        name: horovod
        resources:
          limits:
            cpu: 64
            nvidia.com/gpu: 8
            memory: 96000Mi
        volumeMounts:
        - mountPath: /code
          name: codevolume
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /opt/tf_cnn_benchmarks
          type: DirectoryOrCreate
        name: codevolume

```
output:
```
+ POD_NAME=mpijob-horovod-2-worker-0
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-2-worker-0 -- /bin/sh -c+      PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "379584512" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-[1:2]-launcher-ncdwv,mpijob-horovod-[1:2]-worker-0,mpijob-horovod-[1:2]-worker-1@0(3)" -mca orte_hnp_uri "379584512.0;tcp://192.168.60.207:59751" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
POD_NAME=mpijob-horovod-2-worker-1
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-2-worker-1 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "379584512" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-[1:2]-launcher-ncdwv,mpijob-horovod-[1:2]-worker-0,mpijob-horovod-[1:2]-worker-1@0(3)" -mca orte_hnp_uri "379584512.0;tcp://192.168.60.207:59751" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
begin to training at 2019-03-29 17:19:00

```
and the pod time 
```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 29 Mar 2019 17:17:18 +0800
      Finished:     Fri, 29 Mar 2019 17:20:05 +0800

```

**case B:**
 run tf_cnn_benchmarks.py with pod host-network
the cmd in the worker pod is 
```
/usr/sbin/sshd -p 12345; sleep infinity
```
and cmd  in launcher pod is , IP1 and IP2 is the host IP where worker pods runnig 
```
 - cd /code  && mpirun -np 16 -H IP1:8,IP2:8 -bind-to none -map-by slot -x NCCL_SOCKET_IFNAME=ib0 -mca btl_tcp_if_exclude docker0,tunl0,lo -x NCCL_DEBUG=ERROR -x LD_LIBRARY_PATH -mca plm_rsh_args "-p 12345 -vvvv" python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
```
output:

```
begin to training at 2019-03-29 16:46:29 
```

```
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
       Started:      Fri, 29 Mar 2019 16:46:27 +0800
       Finished:     Fri, 29 Mar 2019 16:47:41 +0800  1分14s
```

so, the costtime of mpirun invoke 
caseA(mpijob)：  1min42s
caseB(host-network) ：  2s

@rongou  
do you have any suggestion about this difference?
I guess it is cause by  the loss of the container network ?
