### ISSUE TITLE
kubectl process in launcher disappear

### ISSUE THREAD

**Issue by soyuutaku** [kubeflow/mpi-operator#108]
I start a MXNet trainning job with horovod, found that kubectl process in launcher disappear after 12 hours or more. Can some one help on how to investigate this???

process in launcher when kubectl gone:
``` log
kubectl exec  mpijob-launcher-vgqnh -- ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  18040  2728 ?        Ss   May07   0:00 /bin/bash -c mpirun --allow-run-as-root -mca btl_tcp_if_include ib0 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod  --prefix /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35 2>&1 | tee -a /log/console.log
root          6  0.0  0.0  18048  2792 ?        S    May07   0:00 /bin/bash /usr/local/bin/mpirun --allow-run-as-root -mca btl_tcp_if_include ib0 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod --prefix /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
root          7  0.0  0.0   4380   752 ?        S    May07   0:01 tee -a /log/console.log
root          8  0.0  0.0 352736  8020 ?        Sl   May07   0:05 mpirun.real --allow-run-as-root --allow-run-as-root -mca btl_tcp_if_include ib0 -bind-to none -map-by slot -mca pml ob1 -mca btl ^openib python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod --prefix /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
root        261  0.0  0.0  34424  2728 ?        Rs   01:51   0:00 ps aux
```

processes in workers:
``` log
kubectl exec  mpijob-worker-0 -- ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0   4376   704 ?        Ss   May07   0:00 sleep 365d
root         16  0.0  0.0   4504   676 ?        Ss   May07   0:00 /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "2533687296" -mca ess_base_vpid 1 -mca ess_base_num_procs "4" -mca orte_node_regex "train-gpu[2:16],amc-tsk-mpijob-[4:2705]-worker-0,amc-tsk-mpijob-[4:2705]-worker-1,amc-tsk-mpijob-[4:2705]-worker-2@0(4)" -mca orte_hnp_uri "2533687296.0;tcp://10.151.154.26,172.10.30.26,172.10.20.26,172.10.40.26,172.17.0.1,10.244.2.0,10.244.2.1:50143" -mca btl_tcp_if_include "ib0" -mca pml "ob1" -mca btl "^openib" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca hwloc_base_binding_policy "none" -mca rmaps_base_mapping_policy "slot" -mca pmix "^s1,s2,cray,isolated"
root         21  0.0  0.0 348612 16420 ?        Sl   May07   0:05 /usr/local/bin/orted -mca ess env -mca ess_base_jobid 2533687296 -mca ess_base_vpid 1 -mca ess_base_num_procs 4 -mca orte_node_regex train-gpu[2:16],amc-tsk-mpijob-[4:2705]-worker-0,amc-tsk-mpijob-[4:2705]-worker-1,amc-tsk-mpijob-[4:2705]-worker-2@0(4) -mca orte_hnp_uri 2533687296.0;tcp://10.151.154.26,172.10.30.26,172.10.20.26,172.10.40.26,172.17.0.1,10.244.2.0,10.244.2.1:50143 -mca btl_tcp_if_include ib0 -mca pml ob1 -mca btl ^openib -mca plm rsh -mca plm_rsh_agent /etc/mpi/kubexec.sh -mca orte_default_hostfile /etc/mpi/hostfile -mca hwloc_base_binding_policy none -mca rmaps_base_mapping_policy slot -mca pmix ^s1,s2,cray,isolated
root         25  299  2.1 53266560 5679940 ?    Sl   May07 3373:44 python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod --prefix /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
root         26  225  2.0 52833116 5521656 ?    Sl   May07 2534:05 python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod --prefix /aiml/dfs/checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
root         27  231  2.1 53546104 5707332 ?    Sl   May07 2606:35 python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod --prefix /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
root         28  296  2.1 53480596 5629780 ?    Sl   May07 3333:56 python -u /code/train_softmax.py --per-batch-size 100 --data-dir /data/ --kv-store=horovod --prefix /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
root     184993  0.0  0.0  34424  2808 ?        Rs   01:40   0:00 ps aux
```

here is my mpiJob yaml:
``` yaml
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  generation: 6
  name: mpijob
  namespace: default
spec:
  backoffLimit: 0
  replicas: 3
  template:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - mpirun --allow-run-as-root -mca btl_tcp_if_include ib0 -bind-to none -map-by
          slot -mca pml ob1 -mca btl ^openib python -u /code/train_softmax.py
          --per-batch-size 100 --data-dir /data/ --kv-store=horovod  --prefix
          /checkpoint/model --network r100 --loss-type 2 --margin-m 0.35
          2>&1 | tee -a /log/console.log
        env:
        - name: NCCL_SOCKET_IFNAME
          value: ib0
        - name: NCCL_DEBUG
          value: INFO
        - name: CUDA_VISIBLE_DEVICES
          value: 0,1,2,3
        - name: MXNET_CPU_WORKER_NTHREADS
          value: "24"
        - name: MXNET_ENGINE_TYPE
          value: ThreadedEnginePerDevice
        image: 10.151.154.101/mxnet/python:horovod-mxnet-master
        name: mpijob
        resources:
          limits:
            nvidia.com/gpu: "4"
          requests:
            nvidia.com/gpu: "4"
        volumeMounts:
        - mountPath: /data/
          name: dataset
        - mountPath: /code/
          name: algorithm
        workingDir: /code/
      hostNetwork: true
      restartPolicy: Nerver
      volumes:
      - name: algorithm
        nfs:
          path: /path/to/runcode
          server: nfs.server
      - name: dataset
        nfs:
          path: /path/to/dataset/
          server: nfs.server

```
