### ISSUE TITLE
When worker's spec add mounting  a pvc, the satefuleset will be build without mountPath 

### ISSUE THREAD

**Issue by b675987273** [kubeflow/mpi-operator#224]
Naturally， the workers are not be created and we can check the statefuleset status.
```
 $kubectl describe  statefulset tensorflow-mnist-tb-worker 
  Warning  FailedCreate      2m52s (x17 over 4m4s)  statefulset-controller  create Pod tensorflow-mnist-tb-worker-0 in StatefulSet tensorflow-mnist-tb-worker failed error: Pod "tensorflow-mnist-tb-worker-0" is invalid: spec.containers[0].volumeMounts[0].mountPath: Required value
```
And the yaml is like this. It is base on the hovorod-cpu example
```
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - command:
            - ""
            image: docker-user.cambricon.com:30080/kubeflow/horovod-cpu:latest
            name: mpi-worker
            volumeMounts:
            - mountpath: /tbdata
              name: pets-data
            resources:
              limits:
                cpu: 2
                memory: 4Gi
          volumes:
          - name: pets-data
            persistentVolumeClaim:
              claimName: pets-pvc

```
