### ISSUE TITLE
Failed to launch MPI Job when specifying gpu request

### ISSUE THREAD

**Issue by cheyang** [kubeflow/mpi-operator#25]
make small changes of mpijob in the example,  only add gpu in requests. The yaml is as below:

```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpi
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: mpioperator/tensorflow-benchmarks:latest
        name: tensorflow-benchmarks
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
```

The launcher job is not created, and checking the mpi-operator logs:

```
E0811 04:53:50.407244       1 mpi_job_controller.go:369] error syncing 'default/mpi-dist-mpijob': Job.batch "mpi-dist-mpijob-launcher" is invalid: spec.template.spec.containers[0].resources.limits: Required value: Limit must be set for non overcommitable resources
```
