### ISSUE TITLE
Using mpi-operator with Intel MPI

### ISSUE THREAD

**Issue by zidarko** [kubeflow/mpi-operator#266]
Hello,

I've been trying to use mpi-operator with Intel MPI. I have a Debian-based container with Intel MPI installed. I have a single master node (pod) and two worker pod. I'm trying to send a simple hello message from each pod.

I'm receiving this error:
```
[mpiexec@mpi-poc-d-launcher-mjmkz] Launch arguments: /etc/mpi/kubexec.sh mpi-poc-d-worker-0 /opt/intel/compilers_and_libraries_2020.1.217/linux
/mpi/intel64/bin//hydra_bstrap_proxy --upstream-host mpi-poc-d-launcher-mjmkz --upstream-port 39712 --pgid 0 --launcher rsh --launcher-number 2
 --launcher-exec /etc/mpi/kubexec.sh --base-path /opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin/ --tree-width 16 --tree-le
vel 1 --time-left -1 --collective-launch 1 --debug --proxy-id 0 --node-id 0 --subtree-size 1 /opt/intel/compilers_and_libraries_2020.1.217/linu
x/mpi/intel64/bin//hydra_pmi_proxy --usize -1 --auto-cleanup 1 --abort-signal 9
[mpiexec@mpi-poc-d-launcher-mjmkz] Launch arguments: /etc/mpi/kubexec.sh mpi-poc-d-worker-1 /opt/intel/compilers_and_libraries_2020.1.217/linux
/mpi/intel64/bin//hydra_bstrap_proxy --upstream-host mpi-poc-d-launcher-mjmkz --upstream-port 39712 --pgid 0 --launcher rsh --launcher-number 2
 --launcher-exec /etc/mpi/kubexec.sh --base-path /opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin/ --tree-width 16 --tree-le
vel 1 --time-left -1 --collective-launch 1 --debug --proxy-id 1 --node-id 1 --subtree-size 1 /opt/intel/compilers_and_libraries_2020.1.217/linu
x/mpi/intel64/bin//hydra_pmi_proxy --usize -1 --auto-cleanup 1 --abort-signal 9
[mpiexec@mpi-poc-d-launcher-mjmkz] check_exit_codes (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:117): unable to run bstrap
_proxy on mpi-poc-d-worker-0 (pid 11, exit code 768)
[mpiexec@mpi-poc-d-launcher-mjmkz] poll_for_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:159): check exit codes error
[mpiexec@mpi-poc-d-launcher-mjmkz] HYD_dmx_poll_wait_for_proxy_event (../../../../../src/pm/i_hydra/libhydra/demux/hydra_demux_poll.c:212): pol
l for event error
[mpiexec@mpi-poc-d-launcher-mjmkz] HYD_bstrap_setup (../../../../../src/pm/i_hydra/libhydra/bstrap/src/intel/i_hydra_bstrap.c:770): error waiti
ng for event
[mpiexec@mpi-poc-d-launcher-mjmkz] main (../../../../../src/pm/i_hydra/mpiexec/mpiexec.c:1956): error setting up the boostrap proxies
```
I'm submitting the command like so:
```
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:

  name: mpi-poc-d
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: library/debian10:intel_mpi_rt
             name: debian-impi-rt
             imagePullPolicy: Never
             command:
                 - mpirun
                 - -v
                 - -np
                 - "2"
                 - -ppn
                 - "1"
                 - -hosts
       	       	 - "mpi-poc-d-worker-0,mpi-poc-d-worker-1"
                 - --launcher
                 - "rsh"
                 - --launcher-exec
                 - "/etc/mpi/kubexec.sh"
       	       	 - sh
       	       	 - -c
       	       	 - 'echo $(hostname):hello'
    Worker:
      replicas: 2
      template:
        spec:
          containers:                                               
          - image: library/debian10:intel_mpi_rt                    
            name: debian-impi-rt
            imagePullPolicy: Never
```

The error message appears to be related to the master node being unable to find the compute nodes. After some further digging I realized the master node is not aware of the existence of the compute nodes i.e. it is unable to ping neither of the two.

What could be wrong?

**Comment by zidarko** [comment]
I create the Docker container using this recipe:
```
 Docker container with Intel MPI runtime libraries
FROM debian:stable-slim as builder

# Requisites
RUN apt-get update \
        && apt-get install make cmake g++ gcc wget gnupg2 ca-certificates apt-transport-https openssh-client --no-install-recommends -y

# Install OpenSSH for MPI to communicate between containers
RUN apt-get install openssh-client openssh-server -y --no-install-recommends \
        && mkdir -p /var/run/sshd

# Allow OpenSSH to talk to containers without asking for confirmation
RUN cat /etc/ssh/ssh_config | grep -v StrictHostKeyChecking > /etc/ssh/ssh_config.new \
        && echo "    StrictHostKeyChecking no" >> /etc/ssh/ssh_config.new \
        && mv /etc/ssh/ssh_config.new /etc/ssh/ssh_config

# Add Intel's repo, install Intel MPI & co.
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
        && apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
        && rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
        && echo deb https://apt.repos.intel.com/mpi all main > /etc/apt/sources.list.d/intel-mpi.list \
        && apt-get update \
        && apt  install intel-mpi-rt-2019.7-217 --no-install-recommends -y \
        && rm -rf /var/lib/apt/lists/*

COPY entrypoint_rt.sh /usr/local/bin/
RUN ln -s /usr/local/bin/entrypoint_rt.sh /

ENV CLASSPATH="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/mpi.jar:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/mpi.jar:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/mpi.jar" \
    FI_PROVIDER_PATH="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib/prov" \
    I_MPI_ROOT="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi" \
    LD_LIBRARY_PATH="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib/release:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/lib" \
    LIBRARY_PATH="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/lib" \
    MANPATH="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/man:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/man:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/man:" \
    PATH="/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/bin:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/bin:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/libfabric/bin:/opt/intel/compilers_and_libraries_2020.1.217/linux/mpi/intel64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Set default shell to /bin/bash
SHELL ["/bin/bash", "-cu"]

ENTRYPOINT ["entrypoint_rt.sh"]
CMD ["/bin/bash"]
```

The script `entrypoint_rt.sh` sets the default paths for libraries though it seems to be ignored by Kubernetes because I replaced the `mpirun` section with simple shell and fired up a simple `export` command that showed the correct libraries were loaded only if I set them explicitly during the creation of the container.

Using the same approach I was able to see that the two compute nodes cannot be reached via `ping` from the master node, which seems to be consistent with the error I'm getting.

I gladly provide more information if needed.

**Comment by zidarko** [comment]
Update:

The solution was to:
1. Edit the file `/etc/mpi/hostfile` and remove the `slots=1` option.
2. Explicitly state the interface to be used like this `-face eth0`.

That's how the launch file looks like now:
```yaml
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: mpi-poc-intelmpi
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template: 
         spec:
           containers:
           - image: library/debian10:intel_mpi_rt
             name: debian-impi
             imagePullPolicy: Never
             command:
              - sh
              - "-c"
              - |
                /bin/bash << 'EOF'
                sed "s/slots=1/ /g" /etc/mpi/hostfile > /root/hostfile
                mpirun  -v -np 2 -f /root/hostfile \
                        -iface eth0 \
                        -launcher rsh \
                        -launcher-exec /etc/mpi/kubexec.sh \
                        sh -c 'echo $(hostname):hello'
                EOF
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: library/debian10:intel_mpi_rt
            name: debian-impi-rt
            imagePullPolicy: Never
```
