### ISSUE TITLE
MPI example not working with volcano scheduler

### ISSUE THREAD

**Issue by yuyue9284** [kubeflow/mpi-operator#284]
This example (https://github.com/kubeflow/mpi-operator/blob/master/examples/v1alpha2/tensorflow-benchmarks.yaml) will pending forever when using volcano scheduler. 

Seems related to this issue:
https://github.com/volcano-sh/volcano/issues/461

**Comment by carmark** [comment]
@yuyue9284 Which Volcano version are you using? And could you post your mpi-operator deployment?

**Comment by yuyue9284** [comment]
> @yuyue9284 Which Volcano version are you using? And could you post your mpi-operator deployment?
> 
> Now, volcano v1.0.0 did change the PodGroup CRD APIGroup to `volcano.sh`, so you may need use mpijob with v1 version which support that PodGroup version. And you need to set `--gang-scheduling` defined at [here](https://github.com/kubeflow/mpi-operator/blob/master/cmd/mpi-operator.v1/app/options/options.go#L70).

Hi carmark, this is my deployment for mpi-operator,
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpi-operator
  namespace: mpi-operator
  labels:
    app: mpi-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mpi-operator
  template:
    metadata:
      labels:
        app: mpi-operator
    spec:
      serviceAccountName: mpi-operator
      containers:
      - name: mpi-operator
        image: mpioperator/mpi-operator:latest
        args: [
          "-alsologtostderr",
          "--kubectl-delivery-image",
          "mpioperator/kubectl-delivery:latest",
          "-gang-scheduling",
          "volcano"
        ]
        imagePullPolicy: Always
```

I'm using mpi-operator v1alpha2 with volcano v0.3, thanks.
