### ISSUE TITLE
How to control the placement of worker replicas?

### ISSUE THREAD

**Issue by cyang49** [kubeflow/mpi-operator#285]
Hi, I have a kubernetes cluster with 4 nodes. I tried to launch an MPI job with 1 launcher and 4 worker replicas. I notice that the worker replicas are placed on 2 of the k8s nodes. Is there a way to control the placement? 

Also, am I right to assume I don't need more than 1 launcher?

Thank you.

**Comment by gaocegege** [comment]
> am I right to assume I don't need more than 1 launcher?

Yes.

> I notice that the worker replicas are placed on 2 of the k8s nodes. Is there a way to control the placement?

If you want gang scheduling, you can have a look at volcano.

**Comment by cyang49** [comment]
> If you want gang scheduling, you can have a look at volcano.

@gaocegege are you saying there isn't a way to control worker placement built-in to kubflow mpi-operator, so I need to use another solution? Is [this](https://github.com/volcano-sh/volcano) what you refer to?

**Comment by gaocegege** [comment]
Yeah, I think so.

**Comment by cyang49** [comment]
Is there any plan to add this feature? That is a bit surprising to me since this is crucial for performance & scalability.

**Comment by gaocegege** [comment]
It is a feature of scheduler. Scheduler is not in the scope of Kubeflow

WDYT @terrytangyuan @carmark

**Comment by cyang49** [comment]
Hi,
I dug around a bit and found that the workers belong to a k8s statefulset. I found that the pod placements can be controlled by using pod affinity/anti-affinity [reference](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) and I tried to insert the following anti-affinity configuration into the MPI job yaml under `Worker` spec:
```
    Worker:
      replicas: 4
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: mpi_role_type
                    operator: In
                    values:
                    - worker
                topologyKey: "kubernetes.io/hostname"
```

This worked and my mpi-workers are placed on different k8s nodes:

```
NAME                      READY   STATUS    RESTARTS   AGE     IP               NODE           NOMINATED NODE   READINESS GATES
lal-dist-launcher-h26gj   1/1     Running   0          5m48s   172.17.115.181   10.240.128.5   <none>           <none>
lal-dist-worker-0         1/1     Running   0          5m48s   172.17.111.39    10.240.128.4   <none>           <none>
lal-dist-worker-1         1/1     Running   0          5m48s   172.17.115.182   10.240.128.5   <none>           <none>
lal-dist-worker-2         1/1     Running   0          5m47s   172.17.116.61    10.240.128.7   <none>           <none>
lal-dist-worker-3         1/1     Running   0          5m47s   172.17.113.158   10.240.128.6   <none>           <none>
``` 

Hope this helps anyone who has similar issues.
