### ISSUE TITLE
Should the limits and requests of the resource(cpu, memory) copy to launcher resource?

### ISSUE THREAD

**Issue by cheyang** [kubeflow/mpi-operator#31]
When I create a MPIJob which specifies cpu and memory, it means Job Launcher also requires such a mount of resources. But it's difficult to allocate such large resource for the Job launcher.

```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpi
spec:
  replicas: 3
  template:
    spec:
      containers:
      - image: mpioperator/tensorflow-benchmarks:latest
        name: tensorflow-benchmarks
        command: ["tail", "-f", "/dev/null"]
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 55
            memory: 120Gi
          requests:
            nvidia.com/gpu: 1
            cpu: 55
            memory: 120Gi
```

How do we handle such issue? The ideas in my head:

1. Remove requests and limits from Job launcher

2. Make Job launcher as worker, it also participates the computation.

@rongou @everpeace @jlewi Can you share your thoughts?
