### ISSUE TITLE
Providing Custom Pod Tolerations throws Error

### ISSUE THREAD

**Issue by asahalyft** [kubeflow/mpi-operator#310]
Hello Team,
We need to provide custom tolerations for GPU pods so that they can be scheduled only on GPU nodes. However, when I apply the custom toleration it fails to parse the mpijob yaml. Following is the yaml used
```
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  name: tf2-keras-mnist-mpi-gpu
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: docker.io/horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu
            name: keras-mnist-mpi-launcher
            command:
            - mpirun
            args:
            - -np
            - "2"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - /examples/tensorflow2_keras_mnist.py
            resources:
              limits:
                cpu: 1
                memory: 2Gi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - name: keras-mnist-mpi-worker
            image: docker.io/horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu
            resources:
              limits:
                nvidia.com/gpu: 1
          tolerations:
          - key: lyft.net/gpu
            operator: Equal
            effect: NoSchedule
            value: dedicated
```

Error shown in
`error: error parsing test.yaml: error converting YAML to JSON: yaml: line 46: found character that cannot start any token`

Line 46 is where the `tolerations` section start.

I am following the https://godoc.org/k8s.io/api/core/v1#PodSpec to understand the PodSpec section.
