### ISSUE TITLE
Does MPIJob allow for p4d.24xlarge node-type in nodeSelector?

### ISSUE THREAD

**Issue by g-karthik** [kubeflow/mpi-operator#314]
I have a Helm chart in which I specify my `MPIJob` to use the AWS p3dn.24xlarge node type as follows:

```
      template:
        spec:
          nodeSelector:
            beta.kubernetes.io/instance-type: {{ .Values.nodeType }}
```

Does MPIJob allow for the new p4d.24xlarge node type to be used here? If not, could support be added for it?
