### ISSUE TITLE
MPI Operator cannot spawn distributed jobs from Python files located on pod mounted volumes

### ISSUE THREAD

**Issue by asahalyft** [kubeflow/mpi-operator#316]
Hello Team,

I have created a custom Horovod image following https://github.com/horovod/horovod/blob/master/Dockerfile.gpu. Image is working fine. 

I am testing out their tensorflow example https://github.com/horovod/horovod/blob/master/examples/tensorflow2/tensorflow2_keras_mnist.py

I have two scenarios:
(1) I keep the `tensorflow2_keras_mnist.py` file embedded inside the docker - this is my relevant docker section
```
# Download Horovod examples
RUN apt-get install -y --no-install-recommends subversion && \
    svn checkout https://github.com/horovod/horovod/trunk/examples $CODE_ROOT/examples && \
    rm -rf $CODE_ROOT/examples/.svn
```

I am able to start and complete the MPI Job because it is reading the tensorflow2_keras_mnist.py from launcher and worker and they have that tensorflow2_keras_mnist.py already embedded inside the container.

(2) I keep the `tensorflow2_keras_mnist.py` file in a mounted volume  `/mnt/user-home/mpi-horovod-exploration`. The MPI Job cannot read from the mounted volume. 

My guess is MPI operator is trying to kick off the mpi job before the Pod has successfully mounted the volumes.

![image](https://user-images.githubusercontent.com/48966647/104624815-e3896b00-5648-11eb-9a64-de38ddc6268f.png)

For complete context this is the mounted volume showing the existence of `tensorflow2_keras_mnist.py`.

![image](https://user-images.githubusercontent.com/48966647/104624499-81306a80-5648-11eb-856d-9b657b9d37b9.png)

This is the complete MPI Job Yaml I applied.

```
# ------- Create GPU Distributed MPI Job ------ #
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata: 
  name: tf2-keras-mnist-mpi-gpu
spec: 
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs: 
    Launcher: 
      replicas: 1
      template: 
        spec: 
          containers: 
            - name: keras-mnist-mpi-launcher
              image: "<hidden-on-purpose>/lyftlearnhorovod:827b89ac94f112bf61bd85621162e93ec9fedcc3"
              command: 
                - mpirun
              args: 
                - "-np"
                - "2"
                - "--allow-run-as-root"
                - "-bind-to"
                - none
                - "-map-by"
                - slot
                - "-x"
                - NCCL_DEBUG=INFO
                - "-x"
                - LD_LIBRARY_PATH
                - "-x"
                - PATH
                - "-x"
                - NCCL_SOCKET_IFNAME=eth0
                - "-mca"
                - pml
                - ob1
                - "-mca"
                - btl
                - ^openib
                - python
                - /mnt/user-home/mpi-horovod-exploration/tensorflow2_keras_mnist.py
              resources: 
                limits: 
                  cpu: 1
                  memory: 2Gi
    Worker: 
      replicas: 2
      template: 
        spec: 
          containers: 
            - name: keras-mnist-mpi-worker
              image: "<hidden-on-purpose>/lyftlearnhorovod:827b89ac94f112bf61bd85621162e93ec9fedcc3"
              resources: 
                limits: 
                  nvidia.com/gpu: 1
          tolerations: 
            - key: lyft.net/gpu
              operator: Equal
              value: dedicated
              effect: NoSchedule
```

**Comment by asahalyft** [comment]
Sorry. My bad. I realized that I have to mount the volumes on the launcher and workers both. For posteriority, if anybody finds this beneficial in future, this is how I mound the volumes on the launcher and workers.

```
# ------- Create GPU Distributed MPI Job ------ #
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata: 
  name: tf2-keras-mnist-mpi-gpu
spec: 
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs: 
    Launcher: 
      replicas: 1
      template: 
        spec:
          containers: 
            - name: keras-mnist-mpi-launcher
              image: "<hidden-on-purpose>/lyftlearnhorovod:96e993ff27c6fc7175e188245ca8a391efd7a553"
              command: 
                - mpirun
              args: 
                - "-np"
                - "2"
                - "--allow-run-as-root"
                - "-bind-to"
                - none
                - "-map-by"
                - slot
                - "-x"
                - NCCL_DEBUG=INFO
                - "-x"
                - LD_LIBRARY_PATH
                - "-x"
                - PATH
                - "-x"
                - NCCL_SOCKET_IFNAME=eth0
                - "-mca"
                - pml
                - ob1
                - "-mca"
                - btl
                - ^openib
                - python
                - /mnt/user-home/mpi-horovod-exploration/tensorflow2_keras_mnist.py
              resources: 
                limits: 
                  cpu: 1
                  memory: 2Gi
              volumeMounts:
              - mountPath: /mnt/user-home
                name: nfs
          volumes:
          - name: nfs
            persistentVolumeClaim:
              claimName: asaha
    Worker: 
      replicas: 2
      template: 
        spec: 
          containers: 
            - name: keras-mnist-mpi-worker
              image: "<hidden-on-purpose>/lyftlearnhorovod:96e993ff27c6fc7175e188245ca8a391efd7a553"
              resources: 
                limits: 
                  nvidia.com/gpu: 1
              volumeMounts:
              - mountPath: /mnt/user-home
                name: nfs
          volumes:
          - name: nfs
            persistentVolumeClaim:
              claimName: asaha
          tolerations: 
            - key: lyft.net/gpu
              operator: Equal
              value: dedicated
              effect: NoSchedule
```
