### ISSUE TITLE
can mpi-operator support horovodrun?

### ISSUE THREAD

**Issue by davidstack** [kubeflow/mpi-operator#327]
mpi-operator support mpirun command, will mpi-operator support howovodrun ? such as

`
horovodrun -np 16 -H server1:4,server2:4,server3:4,server4:4 python train.py
`

**Comment by terrytangyuan** [comment]
If it's fully compatible with mpirun then it should work. Perhaps give it a try?

**Comment by davidstack** [comment]
yes, i have got a test. if i use this command, the job will run successfully. but i do not know whether other horovod functions can work correctly. And we should know the hostname of the worker.
`
horovodrun  -np 2 -H mpi-d3ec808b-worker-0:1,mpi-d3ec808b-worker-1:1  python /horovod/tensorflow_mnist.py
`

**Comment by asahalyft** [comment]
@davidstack I started out with this example - it should be able to run a mpi horovod job on your K8s cluster provides you alreadt have the mpi-operator applied on the K8s cluster.
```
# ------- Create GPU Distributed MPI Job ------ #
apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata: 
  name: tf2-keras-mnist-mpi-gpu
spec: 
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs: 
    Launcher: 
      replicas: 1
      template: 
        spec: 
          containers: 
            - name: keras-mnist-mpi-launcher
              image: "docker.io/horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu"
              command: 
                - mpirun
              args: 
                - "-np"
                - "2"
                - "--allow-run-as-root"
                - "-bind-to"
                - none
                - "-map-by"
                - slot
                - "-x"
                - NCCL_DEBUG=INFO
                - "-x"
                - LD_LIBRARY_PATH
                - "-x"
                - PATH
                - "-x"
                - NCCL_SOCKET_IFNAME=eth0
                - "-mca"
                - pml
                - ob1
                - "-mca"
                - btl
                - ^openib
                - python
                - /examples/tensorflow2_keras_mnist.py
              resources: 
                limits: 
                  cpu: 1
                  memory: 2Gi
    Worker: 
      replicas: 2
      template: 
        spec: 
          containers: 
            - name: keras-mnist-mpi-worker
              image: "docker.io/horovod/horovod:0.19.3-tf2.1.0-torch-mxnet1.6.0-py3.6-gpu"
              resources: 
                limits: 
                  nvidia.com/gpu: 1
          tolerations: 
            - key: lyft.net/gpu
              operator: Equal
              value: dedicated
              effect: NoSchedule
```

You may have to change the `NCCL_SOCKET_IFNAME=eth0` based on your setup.
