### ISSUE TITLE
nodeSelector not working

### ISSUE THREAD

**Issue by kim-sardine** [kubeflow/mpi-operator#358]
When I tried to use `nodeSelector` in MPiJob, it was not working.

I have two types of nodes. each have label like

`"accelerator": "nvidia-v100"`
`"accelerator": "nvidia-p100"`

and when I tried to make below spec, mpijob ran on node with label `"accelerator": "nvidia-p100"`

```yaml
"apiVersion": "kubeflow.org/v1alpha2",
"kind": "MPIJob",
"metadata": {
    "name": mpijob_name,
    "namespace": "mpijob"
},
"spec": {
    "slotsPerWorker": 8,
    "nodeSelector": {
        "accelerator": "nvidia-v100"
    },
    "mpiReplicaSpecs": {
    # ....
```

and I found that there is no `nodeSelector` in MPIJob Spec from [official reference](https://www.kubeflow.org/docs/reference/mpijob/v1alpha2/mpi/)

if it's not supported yet, is there any way possible?
