### ISSUE TITLE
Failed to create MPI worker statefulset when restartPolicy is Never

### ISSUE THREAD

**Issue by cheyang** [kubeflow/mpi-operator#37]
When deploying the following mpijob:

```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpi-dist-mpijob
  labels:
    app: mpijob
spec:
  LauncherOnMaster: true
  replicas: 2
  template:
    metadata:
      name: mpi-dist-mpijob
      labels:
        app: mpijob
        chart: mpijob-0.2.0
        release: mpi-dist
    spec:
      restartPolicy: Never
      containers:
      - image: "uber/horovod:0.13.11-tf1.10.0-torch0.4.0-py3.5"
        name: mpi
        imagePullPolicy:
        workingDir: /root
        command:
        - "sh"
        - "-c"
        - "mpirun python code/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py --model resnet101 --batch_size 64     --variable_update horovod --train_dir=/training_logs --summary_verbosity=3"
        resources:
          requests:
            nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
```

It can't create the MPI workers, reported the error:

```
error syncing 'default/mpi-dist-mpijob': StatefulSet.apps "mpi-dist-mpijob-worker" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"
```

It's caused by the reason that launcher job and statefulset shares the same pod spec, and Statefulset only supports `Always`
