### ISSUE TITLE
Wrong network rules for horovod example

### ISSUE THREAD

**Issue by xhejtman** [kubeflow/mpi-operator#407]
Hello,

I use kubeflow 1.3.0, mpi-operator latest from Jul 5 2021. I tried MPI Job example horovod, however, launcher deployment has error in kubectl-delivery pod:
Failed to list *v1.Pod: Get https://10.43.0.1:443/api/v1/namespaces/adrian/pods?limit=500&resourceVersion=0: dial tcp 10.43.0.1:443: connect: connection refused

I tested, the pod is unable to reach any outer node or external internet on ports 80 or 443. I tested those two workers, they are OK, they can reach anything, one of the workers is running on the same physical node as launcher and worker can reach network, launcher cannot. Launcher can ping interneter (e.g. 8.8.8.8). 

Is it some istio misconfiguration problem? I tried to forcibly start launcher on a different node, result is the same. Thanks for help.

**Comment by xhejtman** [comment]
It seems that the problem is that MPIJob cannot run in istio enabled namespace. In pure namespace, it runs OK. Is this expected? mpi-operator is currently incompatible with istio?

**Comment by xhejtman** [comment]
The problem with istio namespace is, that an istio proxy sidecar is injected. If the istio proxy is not running, no pod can reach network, including init containers. However, istio proxy does not start till all init containers finish. mpi operator runs kubect-delivery initcontainer that needs to access kube api. This is not possible till istio proxy starts. However, the istio proxy does not start until init container finishes. Ergo deadlock. This is famous bug in istio: https://github.com/istio/istio/issues/11130. Situation could be solved, if kubectl-delivery init container forcibly starts before istio-validation init container. Not sure, if this is possible.

**Comment by gaocegege** [comment]
Can you add a label to disable injection?

**Comment by xhejtman** [comment]
I could but I guess it is the same as a new namespace without istio, isn't it? The question is whether the mpi operator can work in istio enabled namespaces or not. If not, maybe it is worth of mention it in README as whole kubeflow framework actually needs istio ;)

**Comment by andreyvelich** [comment]
We disabled istio sidecar for Katib Trials because we are using external source to download dataset: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/mxnet-mnist/mnist.py#L44.
I am not sure if MPI Operator can work with istio enabled.

What do you think @alculquicondor @terrytangyuan ?

**Comment by terrytangyuan** [comment]
I haven't tried it with Istio before so I would recommend adding a note on README regarding this unless others have successful experience with using them together.

**Comment by alculquicondor** [comment]
The v2 controller doesn't have init containers. Please consider giving it a try. I'm currently working on documenting it, but it's already fully functional.

You can build it with

```
make RELEASE_VERSION=dev CONTROLLER_VERSION=v2 images dev_manifest
```

Then you can deploy it with
```
kubectl -k manifests/overlays/dev
```

**Comment by xhejtman** [comment]
Ok, thanks, I will give it a try. Does it use ssh or does it work without root? I am interested in the latter one. Not sure whether to create a new issue or just mention it here, but it seems that if MPI job fails (e.g. due to istio problem) and you delete it and recreate then no pods ever get created on the second try. I need to rename the job.

**Comment by alculquicondor** [comment]
Yes, it uses ssh and it works without root, but you need to make sure the image supports it. See the example in `examples/pi`.

Please open a separate issue with precise steps, wait times, log lines, etc.

**Comment by xhejtman** [comment]
Unfortunately, it requires root for init-ssh container. If you have restrictive PSP, it fails. I try to fix it so it is able to run on PSP enabled cluster and provide patch if interested.

**Comment by xhejtman** [comment]
this is launcher definition:

```
spec:
  containers:
  - args:
    - -n
    - "2"
    - /home/mpiuser/pi
    command:
    - mpirun
    env:
    - name: K_MPI_JOB_ROLE
      value: launcher
    - name: OMPI_MCA_orte_keep_fqdn_hostnames
      value: "true"
    - name: OMPI_MCA_orte_default_hostfile
      value: /etc/mpi/hostfile
    - name: OMPI_MCA_plm_rsh_args
      value: -o ConnectionAttempts=10
    - name: OMPI_MCA_orte_set_default_slots
      value: "1"
    - name: NVIDIA_VISIBLE_DEVICES
    - name: NVIDIA_DRIVER_CAPABILITIES
    image: kubeflow/mpi-pi
    imagePullPolicy: Always
    name: mpi-launcher
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /home/mpiuser/.ssh
      name: ssh-home
    - mountPath: /etc/mpi
      name: mpi-job-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-dkn7g
      readOnly: true
  dnsPolicy: ClusterFirst
  ...
   initContainers:
  - args:
    - -c
    - cp -RL /mnt/ssh/* /mnt/home-ssh && chmod 700 /mnt/home-ssh && chmod 600 /mnt/home-ssh/*
      && chown 1000 -R /mnt/home-ssh
    command:
    - /bin/sh
    image: alpine:3.14
    imagePullPolicy: IfNotPresent
    name: init-ssh
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
```

and I believe, this code should set runasuser for init-ssh container as well, but apparently, it does not.

```
        // The init script sets the permissions of the ssh folder in the user's home
        // directory. The ownership is set based on the security context of the
        // launcher's first container.
        launcherSecurityCtx := job.Spec.MPIReplicaSpecs[kubeflow.MPIReplicaTypeLauncher].Template.Spec.Containers[0].SecurityContext
        initScript := "" +
                "cp -RL /mnt/ssh/* /mnt/home-ssh && " +
                "chmod 700 /mnt/home-ssh && " +
                "chmod 600 /mnt/home-ssh/*"
        if launcherSecurityCtx != nil && launcherSecurityCtx.RunAsUser != nil {
                initScript += fmt.Sprintf(" && chown %d -R /mnt/home-ssh", *launcherSecurityCtx.RunAsUser)
        }
```
