### ISSUE TITLE
SSH issue when trying to deploy horovod mnist example

### ISSUE THREAD

**Issue by ramakrishnamamidi** [kubeflow/mpi-operator#435]
Following is the mpi-operator configuration file i am trying to deploy on our kubernetes cluster.

```
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: tensorflow-mnist
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: horovod/horovod:latest
            name: mpi-launcher
            command:
            - mpirun
            args:
            - -np
            - "2"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - /examples/tensorflow2/tensorflow2_mnist.py
            # resources:
            #   limits:
            #     cpu: 1
            #     memory: 2Gi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: horovod/horovod:latest
            name: mpi-worker
            # resources:
            #   limits:
            #     cpu: 2
            #     memory: 4Gi
```

Following is the error i am getting in the launcher pod
```
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).
Permission denied, please try again.
Permission denied, please try again.
root@tensorflow-mnist-worker-1.tensorflow-mnist-worker: Permission denied (publickey,password).
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   tensorflow-mnist-launcher
  target node:  tensorflow-mnist-worker-0.tensorflow-mnist-worker

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
```

What am i missing as i am unable to find anything on horovod docs or mpi operator 

As per the official docs of [mpi operator](https://www.kubeflow.org/docs/components/training/mpi/)
this config is for tf v1.14 examples/v2beta1/tensorflow-benchmarks.yaml,
The above config is for tfv2.5.0 based on horovod latest docker image. Can anyone tell me what step i am missing.

**Comment by alculquicondor** [comment]
You can use this file as a reference of what configurations the image needs https://github.com/kubeflow/mpi-operator/blob/master/examples/base/Dockerfile

**Comment by victpf** [comment]
I have tried that container, reporting this error for launcher:
  Warning  Failed     16s (x3 over 27s)  kubelet            Error: failed to start container "tensorflow-benchmarks": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"mpirun\": executable file not found in $PATH": unknown @alculquicondor

**Comment by ramakrishnamamidi** [comment]
Ok so I modified the docker image as follows

```
FROM horovod/horovod:latest

RUN echo "UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config && \
    sed -i 's/#\(StrictModes \).*/\1no/g' /etc/ssh/sshd_config
CMD ["/bin/bash"]
```

And used the below mpi config

```
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: tensorflow-mnist
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: ramakrishna1592/mnist-horovod:v1
            name: mpi-launcher
            command:
            - mpirun
            args:
            - -np
            - "2"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - /horovod/examples/tensorflow2/tensorflow2_mnist.py
            # resources:
            #   limits:
            #     cpu: 1
            #     memory: 2Gi
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: ramakrishna1592/mnist-horovod:v1
            name: mpi-worker
            # resources:
            #   limits:
            #     cpu: 2
            #     memory: 4Gi

```

It worked and completed execution in 15m.

Couple of things i noticed, after the mpirun executes the launcher pod goes into CrashLoopBackOff state
![image](https://user-images.githubusercontent.com/13113531/140911769-4b37a5fb-1869-436a-a4dd-7d79f2429a96.png)
Following is the logs of the pod
![image](https://user-images.githubusercontent.com/13113531/140912695-74921c53-5659-414a-94e6-b60423b71fa0.png)

After sometime it moves into running state
![image](https://user-images.githubusercontent.com/13113531/140912524-a6bf5df4-6782-4eb8-9f79-58cf6b5966ca.png)

Is this an issue with the config?? Is there any parameter in need to set
