### ISSUE TITLE
when restartPolicy is set never, launcher pod got into error and started a new one?

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#45]
```
[root@examples]# kubectl get pods -o wide
NAME                            READY     STATUS    RESTARTS   AGE       IP              
mpijob-horovod-launcher-6sv6w   1/1       Running   0          3m        172.16.203.152   
mpijob-horovod-worker-0         1/1       Running   0          6m        172.16.203.151   
mpijob-horovod-worker-1         1/1       Running   0          6m        172.16.216.236  
```

and logs from `launcher` pod show than there is network error between`launcher` and  `worker-1`.
```
[root@offlinetraining-0001 examples]# kubectl logs mpijob-horovod-launcher-6sv6w 
+ POD_NAME=mpijob-horovod-worker-0
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-worker-0 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1679228928" -mca ess_base_vpid 1 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-launcher-6sv6w,mpijob-horovod-worker-0,mpijob-horovod-worker-1@0(3)" -mca orte_hnp_uri "1679228928.0;tcp://172.16.203.152:42479" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
+ POD_NAME=mpijob-horovod-worker-1
+ shift
+ /opt/kube/kubectl exec mpijob-horovod-worker-1 -- /bin/sh -c     PATH=/usr/local/bin:$PATH ; export PATH ; LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH ; export LD_LIBRARY_PATH ; DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH ; export DYLD_LIBRARY_PATH ;   /usr/local/bin/orted -mca ess "env" -mca ess_base_jobid "1679228928" -mca ess_base_vpid 2 -mca ess_base_num_procs "3" -mca orte_node_regex "mpijob-horovod-launcher-6sv6w,mpijob-horovod-worker-0,mpijob-horovod-worker-1@0(3)" -mca orte_hnp_uri "1679228928.0;tcp://172.16.203.152:42479" -mca plm "rsh" -mca plm_rsh_agent "/etc/mpi/kubexec.sh" -mca orte_default_hostfile "/etc/mpi/hostfile" -mca pmix "^s1,s2,cray,isolated"
Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout
Unable to connect to the server: dial tcp 10.96.0.1:443: i/o timeout
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   mpijob-horovod-launcher-6sv6w
  target node:  mpijob-horovod-worker-1

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------

```
after that I saw `launcher` pod go into Error and start a new pod.  

**how can I set  `launcher` pod go into Error and do not start a new pod when error occurs?**

```
[root@examples]# kubectl get pods -o wide
NAME                      READY     STATUS    RESTARTS   AGE       IP               
mpijob-horovod-worker-0   1/1       Running   0          7m        172.16.203.151   
mpijob-horovod-worker-1   1/1       Running   0          7m        172.16.216.236   
[root@examples]# 
[root@examples]# kubectl get mpijob
NAME             AGE
mpijob-horovod   11m
[root@examples]# kubectl get pods -o wide
NAME                            READY     STATUS    RESTARTS   AGE       IP               
mpijob-horovod-launcher-2fjrw   1/1       Running   0          1m        172.16.203.153   
mpijob-horovod-worker-0         1/1       Running   0          7m        172.16.203.151   
mpijob-horovod-worker-1         1/1       Running   0          7m        172.16.216.236   

[root@examples]# kubectl get pods -o wide --show-all
NAME                            READY     STATUS      RESTARTS   AGE       IP               NODE
mpijob-horovod-launcher-2fjrw   0/1       Error       0          11m       172.16.203.153 
mpijob-horovod-launcher-5vr5c   0/1       Error       0          23m       172.16.203.148
mpijob-horovod-launcher-6sv6w   0/1       Error       0          15m       172.16.203.152
mpijob-horovod-launcher-cgz8d   0/1       Error       0          17m       172.16.203.150 
mpijob-horovod-launcher-f2597   1/1       Running     0          2m        172.16.203.155
mpijob-horovod-launcher-jfkkf   0/1       Error       0          7m        172.16.203.154   
mpijob-horovod-launcher-s29qt   0/1       Error       0          20m       172.16.203.149 
mpijob-horovod-worker-0         1/1       Running     0          17m       172.16.203.151   
mpijob-horovod-worker-1         1/1       Running     0          17m       172.16.216.236  
```

**Comment by tingweiwu** [comment]
solved this by setting `  backoffLimit: 0`  
like this:
```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-horovod
spec:
  replicas: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
        command:
          - mpirun
          - python
          - tensorflow_mnist.py
        imagePullPolicy: IfNotPresent
        name: mpijob-horovod
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /examples/MNIST-data-0
          name: datavolume
        - mountPath: /examples/MNIST-data-1
          name: datavolume
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /data/mnist
          type: DirectoryOrCreate
        name: datavolume
```
