### ISSUE TITLE
Can MPI operator no clean on error?

### ISSUE THREAD

**Issue by canshiwei** [kubeflow/mpi-operator#461]
Mpi operator would clean the failed pod. What should I do to prevent it because I would like to read the log when the pod failing

**Comment by alculquicondor** [comment]
Launcher or worker?

Are you already using `.runPolicy.cleanPodPolicy`?

https://github.com/kubeflow/mpi-operator/blob/e267b015aee62648cd2c9f309bdefbca225f09af/v2/pkg/apis/kubeflow/v2beta1/types.go#L48:2

**Comment by alculquicondor** [comment]
That's very odd. Are you using the v2 controller?

**Comment by canshiwei** [comment]
> That's very odd. Are you using the v2 controller?

yes. I'm using v2 controller.  the launcher script (python) I wrote as follows:

1. check passing parameters, if parameters are invalid, exit(1)
2. if parameters are right, run subprocess.run("mpirun -np {} --allow-run-as-root ....", ....)

sometimes I passed a wrong parameter in step 1 before running "mpirun ...", would this cause the launcher pod to be exit and deleted?

**Comment by alculquicondor** [comment]
We just create a `batch/v1.Job` for the launcher. We don't even have code to delete it.

Which environment are you running on? Do you have logs from the apiserver to check what's deleting the pod?

**Comment by alculquicondor** [comment]
This is very odd. The job controller is only supposed to remove pods that are running. Which version of kubernetes are you running?
Can you try to reproduce by creating a Job directly?

**Comment by alculquicondor** [comment]
I just created this job in a 1.23 cluster:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job-c
spec:
  template:
    spec:
      containers:
      - name: sample
        image: bash
        command: ["this_should_fail"]
      restartPolicy: Never
  backoffLimit: 2
```

And I was left with 3 failed pods.

Can you post the yaml for the Job that the mpi-operator created?

**Comment by canshiwei** [comment]
> 

here is mine, the launcher would be deleted:

```
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  generateName: mpi-dnn-
  namespace: power-fl-10000
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 0
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: helloworld:v0.1
            imagePullPolicy: IfNotPresent
            name: mpi-launcher
            command:
            - /bin/bash
            - -exc
            - |
              set +x
              python helloworld.py
    Worker:
      replicas: 2
      template:
        spec:
          containers:
          - image: helloworld:v0.1
            imagePullPolicy: IfNotPresent
            name: mpi-worker
```

and the helloworld:v0.1 is simply 

```
if __name__ == "__main__":
    print("hello world1")
    print("hello world2")
    assert 1 == 2
    print("hello world3")
```

**Comment by alculquicondor** [comment]
can you post the `Job` (not `MPIJob`) that the mpi-operator created?

**Comment by alculquicondor** [comment]
Also, the kubernetes version you are running.

**Comment by canshiwei** [comment]
> restartPolicy: Never

Hi, I explicitly set the 'restartPolicy: Never' as following, but it seems does not work
```
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  generateName: mpi-dnn-
  namespace: fl-10000
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
    backoffLimit: 0
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: helloworld:v0.1
            imagePullPolicy: IfNotPresent
            name: mpi-launcher
            command:
            - /bin/bash
            - -exc
            - |
              set +x
              python helloworld.py
    Worker:
      replicas: 2
      template:
        spec:
          restartPolicy: Never
          containers:
          - image: helloworld:v0.1
            imagePullPolicy: IfNotPresent
            name: mpi-worker
```
