### ISSUE TITLE
Adding back Launcher Init step in v2beta1 helps with ensure pod networking is up before launcher starts

### ISSUE THREAD

**Issue by amrragab8080** [kubeflow/mpi-operator#470]
If i use v2beta1 as is I notice that my job starts after a Crashloopbackoff on the first run.
```
NAME                               READY   STATUS    RESTARTS   AGE
nccl-tests-efa-16-launcher-mkjgm   0/1     Error     0          5s
nccl-tests-efa-16-worker-0         1/1     Running   0          6s
```
then CrashLoopbackOff
```
NAME                               READY   STATUS             RESTARTS      AGE
nccl-tests-efa-16-launcher-mkjgm   0/1     CrashLoopBackOff   1 (15s ago)   22s
nccl-tests-efa-16-worker-0         1/1     Running            0             22s
```
then on next restart it runs normally
```
NAME                               READY   STATUS    RESTARTS      AGE
nccl-tests-efa-16-launcher-mkjgm   1/1     Running   2 (21s ago)   28s
nccl-tests-efa-16-worker-0         1/1     Running   0             28s
```
I seem to be able to over come this problem by adding back the initContainer in the launcher step 
```
spec:
          restartPolicy: OnFailure
          initContainers:
          - image: public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3
            name: init
            command: ["sh", "-c", "sleep 5"]
          containers:
          - image: public.ecr.aws/w6p6i9i7/aws-efa-nccl-rdma:22.03-pt-py3
            imagePullPolicy: Always
            name: nccl-test-launcher
```
i guess this was similar to the v1alpha2 behavior - but wanted to check to see if you think this would cause any compatibly problems?
