### ISSUE TITLE
mpi program only executed on launcher

### ISSUE THREAD

**Issue by o0fatigue** [kubeflow/mpi-operator#472]
Hello, I am trying to use mpi-operator to run a simple hello world mpi program; however, I am confused that instead of running on all the workers, the program is only running on the launcher pod. I have no idea what is wrong with my configuration.

By the way, I also tried to exec into my launcher pod, trying to ssh to a worker pod, but ssh asked me for password although I could see that `id_rsa`, `id_rsa.pub`, and `authorized_keys` are correctly mounted onto all of my launcher and worker pods. `ssh -vvv` log shows that server returned packet type 51, which is "key refused".

YAML:

```yaml
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: hello-mpi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: myimage
            name: hello-mpi
            env:
            - name: LD_LIBRARY_PATH
              value: /softwares/miniconda3/lib
            command:
            - mpirun
            - -np
            - "4"
            - /home/mpi/mpi_hello_world
            resources:
              requests:
                cpu: 4
                memory: 1Gi
    Worker:
      replicas: 4
      template:
        spec:
          containers:
          - image: myimage
            name: hello-mpi
            command: ['/usr/bin/env', 'bash', '-c']
            args:
            - |
              mkdir -p /etc/ssh
              cp /root/.ssh/id_rsa /etc/ssh/ssh_host_rsa_key # this is to avoid "no hostkey error" since I am not using debian distro
              /usr/sbin/sshd -De
            resources:
              requests:
                cpu: 4
                memory: 1Gi
```

Logs on workers:
```
Unable to load host key: /etc/ssh/ssh_host_ecdsa_key
Unable to load host key: /etc/ssh/ssh_host_ed25519_key
Server listening on 0.0.0.0 port 22
Server listening on :: port 22
```

Logs on Launchers:
```
Hello world from processor hello-mpi-launcher, rank 0 out of 0 processors
Hello world from processor hello-mpi-launcher, rank 1 out of 1 processors
Hello world from processor hello-mpi-launcher, rank 2 out of 2 processors
Hello world from processor hello-mpi-launcher, rank 3 out of 3 processors
```

My mpi code:
```c
#include <mpi.h>
#include <stdio.h>

int main(int argc, char** argv) {
    // Initialize the MPI environment
    MPI_Init(NULL, NULL);

    // Get the number of processes
    int world_size;
    MPI_Comm_size(MPI_COMM_WORLD, &world_size);

    // Get the rank of the process
    int world_rank;
    MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);

    // Get the name of the processor
    char processor_name[MPI_MAX_PROCESSOR_NAME];
    int name_len;
    MPI_Get_processor_name(processor_name, &name_len);

    // Print off a hello world message
    printf("Hello world from processor %s, rank %d out of %d processors\n",
           processor_name, world_rank, world_size);

    // Finalize the MPI environment.
    MPI_Finalize();
}
```
