### ISSUE TITLE
Pass on MPIJob annotations to launcher and worker pods

### ISSUE THREAD

**Issue by bimtauer** [kubeflow/mpi-operator#479]
**Expected behavior**

Annotations defined in an MPIJob manifest are passed on to the generated launcher and worker pods. I.e.:

```yaml
kind: MPIJob
metadata:
  annotations:
    foo: "bar"
```
results in
```yaml
kind: Pod
metadata:
  annotations:
    foo: "bar"
  ...
  ownerReferences:
  - apiVersion: kubeflow.org/v2beta1
    ...
    kind: MPIJob
```
Currently this doesn't happen. 

**Why this matters**
Basically for anyone using annotations to manage something of importance in their cluster. In our case kube2iam, vault secret injection and other services rely on annotations and pods spawned by MPI crash because they are lacking needed annotations.
