### ISSUE TITLE
bash: orted: command not found

### ISSUE THREAD

**Issue by gxin0426** [kubeflow/mpi-operator#488]
I get this error when I run the NVIDIA cuquantum quantum simulator with mpi-operator

K8S version: 1.23.6
docker version : 20.10.22

**dockerfile:**
```
FROM nvcr.io/nvidia/cuquantum-appliance:22.11
RUN sed -i 's/[ #]\(.*StrictHostKeyChecking \).*/ \1no/g' /etc/ssh/ssh_config && \
    echo "    UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config && \
    sed -i 's/#\(StrictModes \).*/\1no/g' /etc/ssh/sshd_config
WORKDIR "/examples"
RUN mkdir /run/sshd
ENV CUTENSORNET_COMM_LIB=/opt/conda/lib/libcutensornet_distributed_interface_mpi.so
COPY example22_mpi_auto.py /examples
```

**Yaml:**
```
apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: cuqantum-mpi
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
         spec:
           containers:
           - image: gaoxin2020/cuquantum-mpi-test:v0.1
             name: cuqantum-mpi
             command:
             - mpirun
             - --allow-run-as-root
             - -np
             - "4"
             - python
             - /examples/example22_mpi_auto.py
    Worker:
      replicas: 4
      template:
        spec:
          containers:
          - image: gaoxin2020/cuquantum-mpi-test:v0.1
            name: cuqantum-mpi
            resources:
              limits:
                nvidia.com/gpu: 1
```
**Error:**
```
Warning: Permanently added 'cuqantum-mpi-worker-1.cuqantum-mpi-worker,10.244.0.77' (ECDSA) to the list of known hosts.
Warning: Permanently added 'cuqantum-mpi-worker-3.cuqantum-mpi-worker,10.244.0.80' (ECDSA) to the list of known hosts.
Warning: Permanently added 'cuqantum-mpi-worker-2.cuqantum-mpi-worker,10.244.0.78' (ECDSA) to the list of known hosts.
Warning: Permanently added 'cuqantum-mpi-worker-0.cuqantum-mpi-worker,10.244.0.76' (ECDSA) to the list of known hosts.
bash: orted: command not found
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
--------------------------------------------------------------------------
ORTE does not know how to route a message to the specified daemon
located on the indicated node:

  my node:   cuqantum-mpi-launcher
  target node:  cuqantum-mpi-worker-0.cuqantum-mpi-worker

This is usually an internal programming error that should be
reported to the developers. In the meantime, a workaround may
be to set the MCA param routed=direct on the command line or
in your environment. We apologize for the problem.
--------------------------------------------------------------------------
bash: orted: command not found
bash: orted: command not found
[cuqantum-mpi-launcher:00001] 2 more processes have sent help message help-errmgr-base.txt / no-path
[cuqantum-mpi-launcher:00001] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages

```
