### ISSUE TITLE
NCCL Connection refused when run horovod with mpijob

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#57]
I run tf_cnn_benchmarks.py with horovod in two ways.
(1) with host-network docker as describe in [Horovod in Docker ](https://github.com/uber/horovod/blob/master/docs/docker.md)

```
 on first node
docker run --rm -it --privileged --network=host -v /root/.ssh:/root/.ssh  -v /root/Horovod/local/tf_cnn_benchmarks:/code uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5  bash -c "/usr/sbin/sshd -p 12345; sleep infinity"

on second node
docker run --rm -it --privileged --network=host -v /root/.ssh:/root/.ssh  -v /root/Horovod/local/tf_cnn_benchmarks:/code uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5  mpirun -np 16 -H IP1:8,IP2:8 -bind-to none -map-by slot -x NCCL_SOCKET_IFNAME=ib0 -x NCCL_IB_HCA=mlx5_0 -mca btl_tcp_if_exclude docker0,tunl0,lo -x NCCL_DEBUG=ERROR -x LD_LIBRARY_PATH -mca plm_rsh_args "-p 12345 -vvvv" python /code/tf_cnn_benchmarks.py --model=resnet101 --batch_size=64 --variable_update=horovod
```

(2) with MPIJob as follow
```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-horovod
spec:
  replicas: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
        args:
         - cd /code && mpirun python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
        command:
         - /bin/bash
         - -c
        imagePullPolicy: IfNotPresent
        name: mpijob-horovod
        resources:
          limits:
            nvidia.com/gpu: 8
        volumeMounts:
        - mountPath: /code
          name: codevolume
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /root/Horovod/local/tf_cnn_benchmarks
          type: DirectoryOrCreate
        name: codevolume
```

when I use image `uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5`  
host-network docker and MPIJob both go well.

but when use image `uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5` 

host-network docker run well
but I get NCCL Connection refused error with MPIJob
the error as follow
```
mpijob-horovod-worker-1:16:935 [0] include/socket.h:361 NCCL WARN Call to connect timeout : Connection refused
mpijob-horovod-worker-1:16:935 [0] NCCL INFO transport/net_socket.cu:139 -> 2
mpijob-horovod-worker-1:16:935 [0] NCCL INFO bootstrap.cu:19 -> 2
mpijob-horovod-worker-1:16:935 [0] NCCL INFO bootstrap.cu:225 -> 2
mpijob-horovod-worker-1:16:935 [0] NCCL INFO init.cu:420 -> 2
mpijob-horovod-worker-1:16:935 [0] NCCL INFO init.cu:557 -> 2
```
I also Try
```
cd /code  && mpirun -bind-to none -map-by slot -x NCCL_IB_HCA=mlx5_0 -mca btl_tcp_if_exclude docker0,tunl0,lo  python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
```
and get the same error

I compare the two docker images `uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5` and `uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5`

the difference is 
horovod 0.15.2
```
CUDNN_VERSION=7.3.1.20-1+cuda9.0
NCCL_VERSION=2.3.5-2+cuda9.0
openmpi-3.1.2.tar.gz
```
horovod 0.13.10:
```
CUDNN_VERSION=7.0.5.15-1+cuda9.0
NCCL_VERSION=2.2.12-1+cuda9.0
openmpi-3.0.0.tar.gz
```

all my test case are run on the some nodes. and now I have no idea why I get NCCL Connection refused when I use MPIJob.

Could you give some suggestion? thanks a lot
