### ISSUE TITLE
is the cmd in launcher and worker pod different?

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/mpi-operator#58]
when I start a mpijob as follow
```
apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: mpijob-horovod
spec:
  replicas: 2
  backoffLimit: 0
  template:
    spec:
      containers:
      - image: uber/horovod:0.13.10-tf1.9.0-torch0.4.0-py3.5
        args:
         - cp -rf /code /temp && cd /temp && mpirun python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod
        command:
         - /bin/bash
         - -c
        imagePullPolicy: IfNotPresent
        name: mpijob-horovod
        resources:
          limits:
            nvidia.com/gpu: 8
        volumeMounts:
        - mountPath: /code
          name: codevolume
          readOnly: true
      restartPolicy: Never
      volumes:
      - hostPath:
          path: /root/Horovod/local/tf_cnn_benchmarks
          type: DirectoryOrCreate
        name: codevolume
```

 I get an error `python: can't open file 'tf_cnn_benchmarks.py': [Errno 2] No such file or directory`.
 I check that the ` /temp` dir is existed in launcher  pod but not in the worker.
I guess the cmd `cp -rf /code /temp && cd /temp` have not executed in the worker pod.

when I change cmd into `cd /code && mpirun python tf_cnn_benchmarks.py --model resnet101 --batch_size 64 --variable_update horovod`.  It works well.

so, is the cmd  in launcher and worker pod different?

thanks a lot if you reply
