### ISSUE TITLE
mpijob restarts a few hours after launcher completed.

### ISSUE THREAD

**Issue by ustcyue** [kubeflow/mpi-operator#86]
My job definition is like this. 
```
apiVersion: "kubeflow.org/v1alpha1"
kind: "MPIJob"
metadata:
  name: {{ job_name }}
  labels:
    exp_name: {{ exp_name }}
    user: {{ user_name }}

spec:
  backoffLimit: 0
  ......
      restartPolicy: Never

```
After the launcher job finished, either Failed or Succeed, all worker pods terminated normally. However,  after around three hours, the whole job automatically restarts. Is this expected? Should I delete the mpijob after each run?
